# Generated by Django 3.2.5 on 2022-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=255, unique=True)),
                ('goods_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ship_from', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'goods_info',
            },
        ),
    ]
