# Generated by Django 3.2.5 on 2022-11-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
    ]
